// Shared integration point. Generated by scripts/register-crafting.ts after assets are ready.
import forge1 from './buildings/forge1';
import forge2 from './buildings/forge2';
import forge3 from './buildings/forge3';
import forge4 from './buildings/forge4';
import forge5 from './buildings/forge5';
import garden1 from './buildings/garden1';
import garden2 from './buildings/garden2';
import garden3 from './buildings/garden3';
import home2 from './buildings/home2';
import home3 from './buildings/home3';
import sawmill1 from './buildings/sawmill1';
import sawmill2 from './buildings/sawmill2';
import sawmill3 from './buildings/sawmill3';
import sawmill4 from './buildings/sawmill4';
import training1 from './buildings/training1';
import training2 from './buildings/training2';
import training3 from './buildings/training3';
import warp1 from './buildings/warp1';
import type { CraftPresentation } from './types';

export const BUILD_PRESENTATIONS: Readonly<Record<string, CraftPresentation>> = Object.fromEntries(
  [forge1, forge2, forge3, forge4, forge5, garden1, garden2, garden3, home2, home3, sawmill1, sawmill2, sawmill3, sawmill4, training1, training2, training3, warp1].map((item) => [item.id, item]),
);
