// Shared integration point. Generated by scripts/register-crafting.ts after assets are ready.
import fluffvest from './items/fluffvest';
import type { CraftPresentation } from './types';

export const CRAFT_PRESENTATIONS: Readonly<Record<string, CraftPresentation>> = Object.fromEntries(
  [fluffvest].map((item) => [item.id, item]),
);
