// Standalone report: no server, dependencies or game UI changes. All tables use the same measured dataset.
export function dashboard(data: unknown): string {
  const json = JSON.stringify(data).replaceAll('<', '\\u003c');
  return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sprout Quest — Combat balance</title>
<style>
:root{color-scheme:light;--ink:#283b35;--green:#22684e;--muted:#65726c;--line:#d7ded8;--bad:#9c3434;--paper:#fffdf7}*{box-sizing:border-box}body{margin:0;background:#eef2ec;color:var(--ink);font:15px/1.5 system-ui,sans-serif}main{max-width:1700px;margin:auto;padding:28px}h1{font-size:30px;margin:0 0 8px}h2{font-size:19px}p{max-width:1000px}a{color:var(--green)}.meta,.muted,small{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.card,.panel{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:16px}.card b{display:block;font-size:26px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}button,select,input{font:inherit;color:inherit;border:1px solid #bcc9be;background:#fff;border-radius:7px;padding:8px 10px}button{cursor:pointer}.on{background:var(--green);color:white;border-color:var(--green)}.filters{display:flex;flex-wrap:wrap;gap:12px;align-items:end;margin-bottom:16px}.filters label{display:flex;flex-direction:column;font-size:12px;gap:4px}input[type=checkbox]{width:auto}.check{flex-direction:row!important;align-items:center;font-size:14px!important;padding-bottom:8px}.table-wrap{overflow:auto;max-height:72vh;border:1px solid var(--line);background:var(--paper);border-radius:10px}table{width:100%;border-collapse:collapse;font-size:13px}th{position:sticky;top:0;z-index:1;background:#e5ece4;white-space:nowrap;text-align:left}th,td{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top}td.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}td small{display:block}tr:nth-child(even){background:#f6f7f0}.bad{color:var(--bad);font-weight:650}.good{color:var(--green);font-weight:650}.tag{font-size:11px;padding:2px 6px;border-radius:4px;background:#e4e9e0;display:inline-block}pre{white-space:pre-wrap;font-size:12px;line-height:1.7}.findings{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px}.finding{border-left:4px solid #ba8636}.finding.bug{border-left-color:var(--bad)}.hidden{display:none!important}.pager{display:flex;align-items:center;gap:12px;margin-top:12px}.method li{margin:8px 0}@media(max-width:700px){main{padding:15px}.cards{grid-template-columns:repeat(2,1fr)}h1{font-size:24px}}
</style>
<main>
<h1>Combat balance, measured in the game’s battle engine</h1>
<p class="meta" id="meta"></p>
<p>Compare every weapon at each story stage. Damage, timing, monster movement and weapon effects come from the real combat code. Controller results and stationary attack measurements are shown separately.</p>
<div class="cards" id="cards"></div>
<nav class="tabs" aria-label="Report views"><button class="on" data-view="fights">Fights</button><button data-view="attacks">Attack measurements</button><button data-view="findings">Findings & checks</button><button data-view="economy">Economy & progression</button><button data-view="method">Method & loadouts</button></nav>
<div class="filters" id="shared"><label>Story stage<select id="stage"></select></label><label>Weapon class<select id="style"><option value="all">All classes</option><option>sword</option><option>hammer</option><option>whip</option><option>wand</option></select></label><label>Weapon<select id="weapon"></select></label><label class="check"><input type="checkbox" id="future"> Include future / locked / rematch gear</label></div>
<section id="fights">
<div class="filters"><label>Encounter<select id="kind"><option value="all">All encounters</option><option value="single">Single enemy</option><option value="crowd">Groups</option><option value="golden">Golden enemies</option><option value="boss" selected>Bosses</option></select></label><label>Attack policy<select id="policy"><option value="all">All policies</option><option value="normal">Normals only</option><option value="frequent-special">Frequent special</option><option value="timed-special">Timed special</option></select></label><label>Sort by<select id="sort"><option value="weapon">Weapon / encounter / policy</option><option value="time">Victory time, fastest first</option><option value="dps">Effective DPS, highest first</option><option value="taken">Damage taken, lowest first</option><option value="benefit">Special slowdown, highest first</option></select></label><label>Find enemy<input id="search" placeholder="e.g. Pebblor"></label></div>
<p class="muted">Victory time excludes the entrance animation and includes movement, dodging and hitstop. It describes winning trials only; check win rate beside it. DPS excludes overkill. Positive “special time” means slower than normals. Hover the healing value for its breakdown.</p>
<div class="table-wrap"><table><thead><tr><th>Weapon / handling</th><th>Encounter</th><th>Policy</th><th>Wins</th><th>Victory seconds<br><small>median [10th–90th]</small></th><th>Effective DPS</th><th>Damage taken</th><th>Healing</th><th>HP left</th><th>Potions</th><th>Special time</th><th>Formula seconds<br><small>normal / ideal hits</small></th></tr></thead><tbody id="fight-body"></tbody></table></div>
<div class="pager"><button id="prev">Previous</button><span id="page-label"></span><button id="next">Next</button><a href="fights.csv" download>CSV</a><a href="data.json" download>Full JSON with individual trials</a></div>
</section>
<section id="attacks" class="hidden">
<div class="filters"><label>Handling<select id="handling"><option value="all">All levels</option></select></label><label>Target<select id="target"><option value="slime">Slime</option><option value="golem">Pebblor, armored</option><option value="kingslime">Slime King, large</option></select></label><label>Distance<select id="distance"><option value="all">All distances</option><option>40</option><option selected>70</option><option>130</option><option>220</option></select></label></div>
<p class="muted">Neutral rolls, no crits, level 10 player and targets. One normal attack versus one special, then 3 seconds for native poison/burn and projectiles. “Direct” counts primary hits; “total” includes damage over time. These are not per-second values or a full sword combo. Stage selection controls which weapon tiers are shown, not these fixtures’ level. Secondary targets are 60 units from the primary.</p>
<div class="table-wrap"><table><thead><tr><th>Weapon</th><th>Handling</th><th>Distance</th><th>Normal direct</th><th>Special direct</th><th>Special / normal</th><th>Normal total</th><th>Special total</th><th>Special hits</th><th>First hit seconds<br><small>normal / special</small></th><th>Secondary damage<br><small>normal / special</small></th></tr></thead><tbody id="probe-body"></tbody></table></div>
</section>
<section id="findings" class="hidden"><h2>Behavior checks</h2><div id="checks" class="findings"></div><h2>Balance and controller review flags</h2><p>These flag observations to inspect. Passing behavior checks proves specific mechanics work; it does not certify that the game is balanced.</p><div id="findings-body" class="findings"></div></section>
<section id="economy" class="hidden"><h2>Existing progression and economy estimates</h2><p class="muted">These remain useful planning estimates. The weapon and boss formula tables below omit parts of combat; use the measured Fights and Attack measurements views for combat decisions.</p><div class="panel"><pre id="estimates"></pre></div></section>
<section id="method" class="hidden"><h2>Conditions and limitations</h2><ul id="method-body" class="method"></ul><h2>Stage loadouts</h2><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Player level</th><th>Handling</th><th>Reference weapon</th><th>Armor</th><th>Charm</th><th>Training</th><th>Home</th></tr></thead><tbody id="stage-body"></tbody></table></div><p class="muted">Re-run <code>bun run balance</code> after changing combat. Use <code>--seeds 20</code> for a stronger sample or <code>--fps 20</code> to inspect low frame rates. HTML, CSV and JSON are generated together; this page needs no server or external assets.</p></section>
</main>
<script id="data" type="application/json">${json}</script>
<script>
const D=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>v===null||!Number.isFinite(v)?'—':v.toFixed(d),num=(v,d=1,cls='')=>'<td class="num '+cls+'">'+n(v,d)+'</td>';
$('meta').textContent='Game '+D.version+' · '+new Date(D.generated).toLocaleString()+' · '+D.seeds+' seeds per comparison · '+D.fps+' Hz · Source '+(D.sourceHash||'').slice(0,12);
$('cards').innerHTML=[['Combat trials',D.rows.reduce((s,r)=>s+r.runs,0)],['Comparisons',D.rows.length],['Attack probes',D.probes.length],['Failed mechanics',D.checks.filter(c=>!c.ok).length]].map(([label,v])=>'<div class="card"><span>'+label+'</span><b>'+v.toLocaleString()+'</b></div>').join('');
$('stage').innerHTML='<option value="all">All stages</option>'+D.stages.map(s=>'<option value="'+s.id+'">'+esc(s.label)+'</option>').join('');$('stage').value='woods';
$('weapon').innerHTML='<option value="all">All weapons</option>'+D.weapons.map(w=>'<option value="'+w.id+'">'+esc(w.name)+'</option>').join('');
$('handling').innerHTML+=Array.from({length:10},(_,i)=>'<option>'+String(i+1)+'</option>').join('');$('handling').value='2';
let view='fights',page=0;const SIZE=100;
function matchesWeapon(id){const w=D.weapons.find(w=>w.id===id);if($('weapon').value!=='all'&&id!==$('weapon').value)return false;if($('style').value!=='all'&&w.style!==$('style').value)return false;return true}
function fightRows(){let a=D.rows.filter(r=>matchesWeapon(r.weapon)&&($('stage').value==='all'||r.stage===$('stage').value)&&($('future').checked||r.availability==='stage tier')&&($('kind').value==='all'||r.type===$('kind').value)&&($('policy').value==='all'||r.mode===$('policy').value)&&r.enemy.toLowerCase().includes($('search').value.toLowerCase()));const sort=$('sort').value,order=['normal','frequent-special','timed-special'];a.sort((a,b)=>sort==='time'?(a.winSeconds??Infinity)-(b.winSeconds??Infinity):sort==='dps'?b.activeDps-a.activeDps:sort==='taken'?a.taken-b.taken:sort==='benefit'?(b.specialTimePct??-Infinity)-(a.specialTimePct??-Infinity):a.stage.localeCompare(b.stage)||a.weapon.localeCompare(b.weapon)||a.encounter.localeCompare(b.encounter)||order.indexOf(a.mode)-order.indexOf(b.mode));return a}
function render(){
 if(view==='fights'){
 const rows=fightRows(),pages=Math.max(1,Math.ceil(rows.length/SIZE));page=Math.min(page,pages-1);$('page-label').textContent=rows.length+' comparisons · page '+(page+1)+' / '+pages;$('prev').disabled=page===0;$('next').disabled=page>=pages-1;
 $('fight-body').innerHTML=rows.slice(page*SIZE,(page+1)*SIZE).map(r=>'<tr><td><b>'+esc(r.weaponName)+'</b><small>Handling '+r.handling+' · Player Lv'+r.playerLv+' · '+esc(r.stageName)+'</small><span class="tag">'+esc(r.availability)+'</span></td><td>'+esc(r.enemy)+'<small>'+esc(r.type)+'</small></td><td>'+esc(r.mode)+'</td>'+num(r.winPct,0,r.winPct<100?'bad':'')+'<td class="num">'+n(r.winSeconds)+'<small>['+n(r.p10Seconds)+'–'+n(r.p90Seconds)+']</small></td>'+num(r.activeDps)+num(r.taken)+'<td class="num" title="Life steal '+n(r.lifeSteal)+'; potions '+n(r.potionHealing)+'; regeneration '+n(r.regenHealing)+'">'+n(r.healing)+'<small>Life steal '+n(r.lifeSteal)+'</small></td>'+num(r.hpLeftPct)+num(r.potions)+'<td class="num '+(r.specialTimePct>15?'bad':r.specialTimePct<-10?'good':'')+'">'+(r.specialTimePct===null?'—':(r.specialTimePct>0?'+':'')+n(r.specialTimePct)+'%')+'</td>'+num(r.modeledSeconds)+'</tr>').join('');
 }
 if(view==='attacks'){
 const stage=D.stages.find(s=>s.id===$('stage').value),tier=stage?D.weapons.find(w=>w.id===stage.weapon).tier:5;
 const filtered=D.probes.filter(p=>matchesWeapon(p.weapon)&&($('future').checked||D.weapons.find(w=>w.id===p.weapon).tier<=tier)&&($('handling').value==='all'||p.handling===+$('handling').value)&&p.monster===$('target').value&&($('distance').value==='all'||p.distance===+$('distance').value));
 const normal=new Map(filtered.filter(p=>p.mode==='normal').map(p=>[p.weapon+'/'+p.handling+'/'+p.distance,p]));
 $('probe-body').innerHTML=filtered.filter(p=>p.mode==='special').map(s=>{const a=normal.get(s.weapon+'/'+s.handling+'/'+s.distance),ratio=a.direct?s.direct/a.direct:null;return '<tr><td>'+esc(D.weapons.find(w=>w.id===s.weapon).name)+'</td>'+num(s.handling,0)+num(s.distance,0)+num(a.direct,0)+num(s.direct,0)+'<td class="num '+(ratio!==null&&ratio<.8?'bad':'')+'">'+(ratio===null?'—':n(ratio*100,0)+'%')+'</td>'+num(a.total,0)+num(s.total,0)+num(s.hits,0)+'<td class="num">'+n(a.firstHit,2)+' / '+n(s.firstHit,2)+'</td><td class="num">'+n(a.secondary,0)+' / '+n(s.secondary,0)+'</td></tr>'}).join('');
 }
}
for(const id of ['stage','style','weapon','future','kind','policy','sort','search','handling','target','distance'])$(id).addEventListener('input',()=>{page=0;render()});
$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view=b.dataset.view;for(const x of document.querySelectorAll('[data-view]'))x.classList.toggle('on',x===b);for(const id of ['fights','attacks','findings','economy','method'])$(id).classList.toggle('hidden',id!==view);$('shared').classList.toggle('hidden',!['fights','attacks'].includes(view));render()};
$('checks').innerHTML=D.checks.map(c=>'<div class="panel finding '+(c.ok?'':'bug')+'"><b class="'+(c.ok?'good':'bad')+'">'+(c.ok?'PASS':'FAIL')+' · '+esc(c.label)+'</b><p>'+esc(c.observed)+'</p></div>').join('');
$('findings-body').innerHTML=D.findings.filter(f=>f.severity!=='bug').map(f=>'<div class="panel finding"><b>'+esc(f.title)+'</b><p>'+esc(f.text)+'</p></div>').join('');
$('method-body').innerHTML=D.assumptions.map(s=>'<li>'+esc(s)+'</li>').join('');$('estimates').textContent=D.estimates;
$('stage-body').innerHTML=D.stages.map(s=>'<tr><td>'+esc(s.label)+'</td>'+num(s.lv,0)+num(s.handling,0)+'<td>'+esc(s.weapon)+'</td><td>'+esc(s.armor)+'</td><td>'+esc(s.charm||'none')+'</td>'+num(s.training||0,0)+num(s.home||1,0)+'</tr>').join('');
render();
</script></html>`;
}
