// Run once during integration after individual geometry, metadata and assets arrive.
// Workers never need to edit the shared catalog themselves.
import { writeFile } from 'node:fs/promises';
import type { CraftPresentation } from '../src/crafting/types';

const files = [...new Bun.Glob('*.ts').scanSync('src/crafting/items')].sort();
const names: string[] = [];
for (const file of files) {
  const item: CraftPresentation = (await import(`../src/crafting/items/${file}`)).default;
  const id = file.slice(0, -3);
  if (item.id !== id || !/^[a-z][a-z0-9]*$/.test(id)) throw new Error(`${file}: export id must match the gear id/filename`);
  for (const src of [...item.layers.map((p) => p.src), item.complete]) {
    if (!await Bun.file(`public/${src}`).exists()) throw new Error(`${id}: missing ${src}`);
  }
  names.push(id);
}
await writeFile('src/crafting/catalog.ts', `// Shared integration point. Generated by scripts/register-crafting.ts after assets are ready.\n${names.map((id) => `import ${id} from './items/${id}';`).join('\n')}\nimport type { CraftPresentation } from './types';\n\nexport const CRAFT_PRESENTATIONS: Readonly<Record<string, CraftPresentation>> = Object.fromEntries(\n  [${names.join(', ')}].map((item) => [item.id, item]),\n);\n`);
console.log(`Registered ${names.length} crafting presentations. Run typecheck and tests before publication.`);
