// Run once during integration after individual geometry, metadata and assets arrive.
// Workers never need to edit the shared catalog themselves.
// Gear, tools, potions and meals come from src/crafting/items; village project levels (`<project><level>.ts`, e.g.
// home2) from src/crafting/buildings.
import { writeFile } from 'node:fs/promises';
import type { CraftPresentation } from '../src/crafting/types';

async function register(folder: string, catalog: string, name: string, what: string) {
  const files = [...new Bun.Glob('*.ts').scanSync(`src/crafting/${folder}`)].sort();
  const names: string[] = [];
  for (const file of files) {
    const item: CraftPresentation = (await import(`../src/crafting/${folder}/${file}`)).default;
    const id = file.slice(0, -3);
    if (item.id !== id || !/^[a-z][a-z0-9]*$/.test(id)) throw new Error(`${file}: export id must match the ${what} id/filename`);
    for (const src of [...item.layers.map((p) => p.src), item.complete]) {
      if (!await Bun.file(`public/${src}`).exists()) throw new Error(`${id}: missing ${src}`);
    }
    names.push(id);
  }
  await writeFile(`src/crafting/${catalog}.ts`, `// Shared integration point. Generated by scripts/register-crafting.ts after assets are ready.\n${names.map((id) => `import ${id} from './${folder}/${id}';`).join('\n')}\nimport type { CraftPresentation } from './types';\n\nexport const ${name}: Readonly<Record<string, CraftPresentation>> = Object.fromEntries(\n  [${names.join(', ')}].map((item) => [item.id, item]),\n);\n`);
  return names.length;
}

const items = await register('items', 'catalog', 'CRAFT_PRESENTATIONS', 'gear');
const buildings = await register('buildings', 'building-catalog', 'BUILD_PRESENTATIONS', 'project level');
console.log(`Registered ${items} crafting and ${buildings} building presentations. Run typecheck and tests before publication.`);
